export const ROLES = {
  ADMIN: "ADMIN",
  QA_MANAGER: "QA_MANAGER",
  QA_COORDINATOR: "QA_COORDINATOR",
  DEPARTMENT_MANAGER: "DEPARTMENT_MANAGER",
  HR_MANAGER: "HR_MANAGER",
  ACADEMIC: "ACADEMIC",
  SUPPORT: "SUPPORT",
};