export const ROLES = {
  ADMIN: "ADMIN",
  QA_MANAGER: "QA_MANAGER",
  QA_COORDINATOR: "QA_COORDINATOR",
  DEPT_MANAGER: "DEPT_MANAGER",
  HR_MANAGER: "HR_MANAGER",
  HEAD: "HEAD",
  ACADEMIC_STAFF: "ACADEMIC_STAFF",
  SUPPORT_STAFF: "SUPPORT_STAFF",
};