spring.application.name=comp1640
spring.jackson.property-naming-strategy=SNAKE_CASE

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/comp1640?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Admin123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=./uploads

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

jwt.secret=comp1640-secret-key-1234567890-abcdef-xyz
jwt.expiration=86400000

spring.thymeleaf.cache=false
server.port=8080

cloudinary.cloud-name=dfnyvfiuq
cloudinary.api-key=722446538895148
cloudinary.api-secret=E8RB0nF6TxAKQ3SWmZ5lKkbZvpg


